//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RA01.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AircraftSighting
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Please Enter Make")]
        public string Make { get; set; }
        [Required(ErrorMessage = "Please Enter Model")]
        public string Model { get; set; }
        [Required(ErrorMessage = "Please Enter Registration")]
        public string Registration { get; set; }
        [Required(ErrorMessage = "Please Enter Location")]
        public string Location { get; set; }
        [Required(ErrorMessage = "Please Enter DateAndTime")]
        public System.DateTime DateAndTime { get; set; }
        public string ImgFilePath { get; set; }
    }
}
